language: python

python:
- 3.7
- 3.8

before_install:
- pip install --upgrade setuptools pip

install:
- pip install --editable .

script:
- python -m pytest -vvv jupyter-resource-usage


jobs:
  include:
    - name: autoformatting check
      python: 3.6
      # NOTE: It does not suffice to override to: null, [], or [""]. Travis will
      #       fall back to the default if we do.
      before_install: echo "Do nothing before install."
      install: pip install pre-commit
      script:
        - pre-commit run --all-files
      after_success: echo "Do nothing after success."
      after_failure:
        - |
          echo "You can install pre-commit hooks to automatically run formatting"
          echo "on each commit with:"
          echo "    pre-commit install"
          echo "or you can run by hand on staged files with"
          echo "    pre-commit run"
          echo "or after-the-fact on already committed files with"
          echo "    pre-commit run --all-files"
